var instruments = [ 
    {
        textContent: "Housle staccato",
        category: "strings",
        id: "strings-stac-high",
        path: './tracks/mp3/stringsStacHigh.mp3',
        icon: '<i class="flaticon-violin"></i>',
        initial: false,
    },
   {
       textContent: "Violoncello staccato",
       category: "strings",
        id: "strings-stac-mid",   
        path: './tracks/mp3/stringsStacMid.mp3',
        icon: '<i class="flaticon-cello"></i>',
        initial: false,
    },
   {
       textContent: "Kontrabas staccato",
       category: "strings",
        id: "strings-stac-low",   
        path: './tracks/mp3/stringsStacLow.mp3',
        icon: '<i class="flaticon-double-bass"></i>',
        initial: false,
    },
   {
       textContent: "Smyčcová sekce sustain",
       category: "strings",
        id: "strings-sus",   
        path: './tracks/mp3/stringsSus.mp3',
        icon: '<i class="flaticon-violin"></i>',
        initial: true,
    },
    {
        textContent: "Lesní roh",
        category: "winds",
        id: "french-horn",
        path: './tracks/mp3/frenchHorn.mp3',
        icon: '<i class="flaticon-french-horn"></i>',
        initial: false,
    },
   {
       textContent: "Sbor",
       category: "voice",
        id: "choir",   
        path: './tracks/mp3/choir.mp3',
        icon: '<i class="far fa-user"></i>',
        initial: false,
    },
   {
       textContent: "Klavír",
       category: "percussion",
        id: "piano",   
        path: './tracks/mp3/piano.mp3',
        icon: '<i class="flaticon-piano"></i>',
        initial: false,
    },
    {
        textContent: "Tympány",
        category: "percussion",
        id: "timpani",
        path: './tracks/mp3/timpani.mp3',
        icon: '<i class="flaticon-drum-1"></i>',
        initial: false,
    },
    {
        textContent: "Činely",
        category: "percussion",
        id: "cymbals",
        path: './tracks/mp3/cymbals.mp3',
        icon: '<i class="flaticon-cymbals"></i>',
        initial: false,
    },
    {
        textContent: "Zvonkohra",
        category: "percussion",
        id: "glockenspiel",
        path: './tracks/mp3/glockenspiel.mp3',
        icon: '<i class="flaticon-xylophone"></i>',
        initial: true,
    },
    {
        textContent: "Dechová sekce",
        category: "winds",
        id: "flute",
        path: './tracks/mp3/woodwinds.mp3',
        icon: '<i class="flaticon-flute-2"></i>',
        initial: false,
    },
];