var instruments = [ 
    {
        textContent: "Violin Staccato",
        category: "strings",
        id: "strings-stac-high",
        path: '../tracks/mp3/stringsStacHigh.mp3',
        icon: '<i class="flaticon-violin"></i>',
        initial: false,
    },
   {
       textContent: "Cello Staccato",
       category: "strings",
        id: "strings-stac-mid",   
        path: '../tracks/mp3/stringsStacMid.mp3',
        icon: '<i class="flaticon-cello"></i>',
        initial: false,
    },
   {
       textContent: "Double-Bass Staccato",
       category: "strings",
        id: "strings-stac-low",   
        path: '../tracks/mp3/stringsStacLow.mp3',
        icon: '<i class="flaticon-double-bass"></i>',
        initial: false,
    },
   {
       textContent: "String Section Sustain",
       category: "strings",
        id: "strings-sus",   
        path: '../tracks/mp3/stringsSus.mp3',
        icon: '<i class="flaticon-violin"></i>',
        initial: true,
    },
    {
        textContent: "French Horn",
        category: "winds",
        id: "french-horn",
        path: '../tracks/mp3/frenchHorn.mp3',
        icon: '<i class="flaticon-french-horn"></i>',
        initial: false,
    },
   {
       textContent: "Choir",
       category: "voice",
        id: "choir",   
        path: '../tracks/mp3/choir.mp3',
        icon: '<i class="far fa-user"></i>',
        initial: false,
    },
   {
       textContent: "Grand Piano",
       category: "percussion",
        id: "piano",   
        path: '../tracks/mp3/piano.mp3',
        icon: '<i class="flaticon-piano"></i>',
        initial: false,
    },
    {
        textContent: "Timpani",
        category: "percussion",
        id: "timpani",
        path: '../tracks/mp3/timpani.mp3',
        icon: '<i class="flaticon-drum-1"></i>',
        initial: false,
    },
    {
        textContent: "Cymbals",
        category: "percussion",
        id: "cymbals",
        path: '../tracks/mp3/cymbals.mp3',
        icon: '<i class="flaticon-cymbals"></i>',
        initial: false,
    },
    {
        textContent: "Glockenspiel",
        category: "percussion",
        id: "glockenspiel",
        path: '../tracks/mp3/glockenspiel.mp3',
        icon: '<i class="flaticon-xylophone"></i>',
        initial: true,
    },
    {
        textContent: "Woodwinds",
        category: "winds",
        id: "flute",
        path: '../tracks/mp3/woodwinds.mp3',
        icon: '<i class="flaticon-flute-2"></i>',
        initial: false,
    },
];
